### ISSUE TITLE
Recomendación: Bienvenida e instrucciones

### ISSUE THREAD

**Issue by Zakuhest** [joe7hann/trivia_ABCsilabuz#1]
**Descripción de Recomendación:**

Entre las lineas 23 y 33 de la bienvenida e instrucciones que introducen a la trivia, específicamente en la línea 29, recomendaría aumentar el tiempo dado para la información presentada para que el usuario tenga tiempo suficiente para leerlo y no generar confusión. 

```
#Bienvenida
print(CYAN+'█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█'+RESET)
print(CYAN+"█░░"+RESET,"  Bienvenido a ",CYAN+"░░█"+RESET)
print(CYAN+"█░░"+RESET,"  la trivia    ",CYAN+"░░█"+RESET)
print(CYAN+"█░░"+RESET,"CAMINO DEL INKA",CYAN+"░░█"+RESET)
print(CYAN+"█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█"+RESET)
time.sleep(2)

nombre = input(CYAN +"\nCual es tu nombre: "+RESET)

print(MAGENTA+"Hola",nombre,"\nEn este juego, eres un Viajero del tiempo y llegas a 1532, en la llegada de los espanoles a cajamarca. \nComo CHASKI tienes la responsabilidad de avisar a Cusco la llegada de los espanoles al Tahuantinsuyo."+RESET)
```

De igual forma, en las líneas del inicio de la trivia, específicamente en las líneas 57, 58 y 64.

```
while iniciar_trivia == True:
  print("\nLa Trivia comenzara en:")
  for x in range (5,0,-1):
    print(RED,x,RESET)
    time.sleep(1)
  time.sleep(1)
  os.system("cls" if os.name == "nt" else "clear")
  print(GREEN+"██╗░░░░░███████╗████████╗  ░██████╗░░█████╗░██╗\n██║░░░░░██╔════╝╚══██╔══╝  ██╔════╝░██╔══██╗██║\n██║░░░░░█████╗░░░░░██║░░░  ██║░░██╗░██║░░██║██║\n██║░░░░░██╔══╝░░░░░██║░░░  ██║░░╚██╗██║░░██║╚═╝\n███████╗███████╗░░░██║░░░  ╚██████╔╝╚█████╔╝██╗\n╚══════╝╚══════╝░░░╚═╝░░░  ░╚═════╝░░╚════╝░╚═╝"+RESET)
  time.sleep(1)
  os.system("cls" if os.name == "nt" else "clear")
  print(YELLOW+"Tu puntaje inicial es de:", puntaje,"puntos"+RESET)
  time.sleep(1)
```

 **A Realizar:**

Modificar o actualizar las líneas con un valor de parametro mayor que 1 o 2, para otorgar un mejor tiempo de lectura del usuario.

**Comment by joe7hann** [comment]
# Fixed:
* Se aumentó un tiempo de espera de 7 segundos en la línea 34, ya que en la línea 33 se presenta la temática del juego.
* El tiempo en la línea 64 se incrementa a 5 segundos.

# Not planet:
## reasons:
* Las líneas 57 y 58 no se modifican ya que representan un tiempo de 5 segundos

**Comment by joe7hann** [comment]
Fixed
