### ISSUE TITLE
Bug: Error en puntaje

### ISSUE THREAD

**Issue by Zakuhest** [joe7hann/trivia_ABCsilabuz#2]
**Descripción del Bug:**

Entre las lineas 72 y 80 en el cálculo del tiempo tomado para resolver cada pregunta de la trivia, específicamente en la línea 79, en caso de que el tiempo en el que se demora en responder sea muy grande, se tomará ese valor para calcular el puntaje.

```
for x in range(3,0,-1):
    print(RED,"Responde en:",x,RESET)
    time.sleep(1)
  t0 = time.time()
  respuesta_1 = input("\nIngresa tu respuesta: ")
  
  t1 = time.time()
  tf = round(t1-t0,2)#timepo final
  print ("Te demoraste", tf,"segundos, en responder la pregunta")
```

En la línea 87,  se calcula el puntaje haciendo una resta al tiempo en el que se ha demorado, por lo que si el tiempo calculado es mayor al puntaje base (valor 10), el resultado sería un número negativo muy grande. Esto dificultaría ganar puntaje al usuario por pregunta bien respondida.

```
# verificacion de respuesta
  if respuesta_1 == "c":
    puntaje+= 10 -tf
    print("Correcto,", nombre,"bien hecho!\n")
    print(YELLOW,"Tu puntaje es de:",puntaje,"puntos",RESET)
  else:
    print("Inconrrecto")
  time.sleep(3)
  os.system("cls" if os.name == "nt" else "clear")
```

**A Realizar:**

Corregir las líneas, colocando un límite de tiempo de respuesta a la pregunta de forma que el puntaje no termine siendo un número negativo o un valor negativo muy grande.

**Comment by joe7hann** [comment]
# Bug fixed
* Se corrigió el tiempo, dándole un máximo de 9 segundos. Después de este tiempo, podrá responder a la pregunta, sin embargo, no se descontarán más puntos.
* En la línea 93 se agregó time.sleep(5), para que el jugador pueda ver el tiempo que tomó y la puntuación actual.
