### ISSUE TITLE
Recomendación: Ortografía

### ISSUE THREAD

**Issue by Zakuhest** [joe7hann/trivia_ABCsilabuz#3]
**Descripción de Recomendación:**

Alrededor de la trivia hay pequeños errores ortográficos en las preguntas, que dificultarían el entendimiento del jugador.

Ejemplo:

```
  print(MAGENTA+"\n3) Quien? escribio la obra 'Los comentarios reales'?"+RESET)
  print(GREEN+"a.Mario Vargas Llosa")
  print("b.Inca Garcilazo de la Vega")
  print("c.Cesar Acunha")
  print("d.Friedrich Nietzsche"+RESET)

```
**A Realizar:**

Modificar o actualizar las líneas que describen las preguntas de la trivia, y corregir los pequeños errores ortográficos.

**Comment by joe7hann** [comment]
# Fixed
* Se corrigió las faltas ortográficas, para mejor experiencia del jugador.
